name: Docker Image CI

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'ghcr.io/eurofiber-cloudinfra/azure-url-monitor'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out 
      uses: actions/checkout@v3

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: $IMAGE_NAME
        tag-sha: true
        tag-edge: false
        tag-latest: true    

    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.lowercase.tags }}
        file: ./docker/Dockerfile