name: Docker Image CI

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: 'azure-urlmonitor'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        set -x
        docker build . --file docker/Dockerfile --tag $IMAGE_NAME:${{ github.ref }}