name: Docker Image CI

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out 
      uses: actions/checkout@v3

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    # change repo name to lower case
    - uses: ASzc/change-string-case-action@v2
      id: image_name
      with:
        string: ${{ github.repository }}

    - name: Build and Push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}:latest
        file: ./docker/Dockerfile